owner: thoangdev
repo: dispel-uptime

sites:
  - name: Dispel STIG
    url: https://dashboard.dispel.io/
  - name: ABB
    url: https://secureremote.abb.com/
  - name: MCC
    url: https://mcc.dispel.io/
  - name: ESTEE
    url: https://ztogateway.elcompanies.com/
    method: GET
    expectStatus: 200
    options:
      rejectUnauthorized: false

status-website:
  baseUrl: /dispel-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dispel PROD Uptime Monitor
  introTitle: "**Dispel Uptime Monitor**"
  introMessage: This site shows live uptime and response stats for Dispel systems.
  navbar:
    - title: Advertisement
      href: https://thoangdev.github.io/
    - title: GitHub
      href: https://github.com/thoangdev/dispel-uptime
