owner: thoangdev
repo: dispel-uptime

sites:
  - name: Dispel STIG
    url: https://dashboard.dispel.io/

status-website:
  baseUrl: /dispel-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dispel Uptime Monitor
  introTitle: "**Dispel Uptime Monitor**"
  introMessage: This site shows live uptime and response stats for Dispel systems.
  navbar:
    - title: Status
      href: https://thoangdev.github.io/dispel-uptime/
    - title: GitHub
      href: https://github.com/thoangdev/dispel-uptime
